### ISSUE TITLE
Create a new page for online resources.

### ISSUE THREAD

**Issue by ballen38-creator** [ballen38-creator/studentcorner#10]
The page design should be like this -
![image](https://user-images.githubusercontent.com/72469365/135800953-43eb42ad-8afd-466a-914f-b7a575d6d505.png)

However, there need to be the following changes - 
[ ] There's no need of a new navbar, the default navbar of all other pages should be used but colors can be adjusted to preference.
[ ] The page should be responsive.
[ ] The social icons in the top right corner should be removed.
[ ] There should be 7 different sections on the page listed like how in the image 'latest is marked'
[ ] The name of the 7 different sections are - 'Artificial Intelligence', 'Cyber and Network Security', 'Distributed Systems', 'Computer Graphics and Multimedia', 'Python' ,'Scripting Languages' and 'Information and Storage Management'.
[ ] For video cards use any appropriate thumbnail and description.
[ ] The video cards are expected to be <iframe> but they could work as a hyperlink to video.

**When submitting a pull request checkmark the changes you were able to complete from the above. Good luck👍**

**Comment by abhirv08-1** [comment]
@ballen38-creator please asssign it to me.

**Comment by AkhilChoubey** [comment]
Hello, @ballen38-creator , I can work on this request , please clear mine doubt about , where can I find the video resources links, or I need to simply add random links which will later edited by you? 

Other than this there is no doubt , Please Assign this issue to me , so that I can start working on this asap ... Thanks!!

**Comment by ballen38-creator** [comment]
> Hello, @ballen38-creator , I can work on this request , please clear mine doubt about , where can I find the video resources links, or I need to simply add random links which will later edited by you?
> 
> Other than this there is no doubt , Please Assign this issue to me , so that I can start working on this asap ... Thanks!!

You don't need to add video links now, just create video cards to display which can work with any demo image and description. Also create this in a separate file named 'resources.html' .

**Comment by AkhilChoubey** [comment]
Cool ! I will get back to you , once I am done with this task..

**Comment by AkhilChoubey** [comment]
I have implemented the recourses page and kinding merge the pr with hacktoberfest-accepted lable. Thank You!

You can Contact me for any clearance.

**Comment by ballen38-creator** [comment]
> I have implemented the recourses page and kinding merge the pr with hacktoberfest-accepted labele. Thank You!
> 
> You can Contact me for any clearance.

I have merged the file under hacktoberfest and hacktoberfestfest-accepted label. Thankyou for your contribution. Great work!

**Comment by ballen38-creator** [comment]
This issue has been resolved by @AkhilChoubey.
