### ISSUE TITLE
Remove padding from navbar on all pages.

### ISSUE THREAD

**Issue by ballen38-creator** [ballen38-creator/studentcorner#14]
Currently due to navbar padding by bootstrap class of 'py-3', the navbar overlaps some section of the site. Your task is to remove the padding class 'py-3' from all the pages of the site. Also add the link to resources page in navbar of each subject page like it's present in the index.html file.

**Comment by random3900** [comment]
Can I please work on this issue?

**Comment by ballen38-creator** [comment]
> Can I please work on this issue?

Go fot it.
