### ISSUE TITLE
Make the '.nav-item: hover' effect specific to '.nav-pill' class items.

### ISSUE THREAD

**Issue by ballen38-creator** [ballen38-creator/studentcorner#15]
The hover class of '.nav-item' in style.css should only affect the subject names but as of now it is also getting applied to navbar links. Solve this issue by making the hover effect specific to items included in the '.nav-pill' class.

**Comment by bstuff** [comment]
@ballen38-creator please review

**Comment by Eddievin** [comment]
Worked on this - please review the pull request.

**Comment by Eddievin** [comment]
> @ballen38-creator please review

hey, sorry I have just seen this. Let me close my pull request ASAP.
