### ISSUE TITLE
Add an icon in navbar

### ISSUE THREAD

**Issue by ballen38-creator** [ballen38-creator/studentcorner#3]
Add this icon in navbar for all the subject pages.
icon  - [https://img.icons8.com/fluency/48/000000/student-female.png](url)

**Comment by harshalw07** [comment]
Added the given icon into the index.html.
Aligned properly and wrapped in the **img tag** with a proper class.
![Capture](https://user-images.githubusercontent.com/88126857/135754382-8d40fe79-d37e-4339-9a68-915bcc181ed1.PNG)

**Comment by Aditya31077** [comment]
I can do this. Please  assign me this project.

**Comment by aniket1104** [comment]
i have contributed previously too ...and i can fic the issue...please assign me the task.

**Comment by ballen38-creator** [comment]
> i have contributed previously too ...and i can fic the issue...please assign me the task.

Sorry, but he asked first but don't worry I will try to open some more issues tomorrow for you to contribute.

**Comment by ballen38-creator** [comment]
> I can do this. Please assign me this project.

Alright, let's see what you come up with ?

**Comment by aniket1104** [comment]
> > i have contributed previously too ...and i can fic the issue...please assign me the task.
> 
> Sorry, but he asked first but don't worry I will try to open some more issues tomorrow for you to contribute.

> no problem...i can wait for the new issues :)

**Comment by harshalw07** [comment]
this issue is cleared by me isn't it ?

**Comment by ballen38-creator** [comment]
> this issue is cleared by me isn't it ?

yup but I edited some details because I want the nav icon on every subjects page. Don't worry your contribution to the index page still counts.

**Comment by ballen38-creator** [comment]
This issue has been resolved.

**Comment by harshalw07** [comment]
It is considered in hacktober also ??
