### ISSUE TITLE
add new design for subjects section

### ISSUE THREAD

**Issue by ballen38-creator** [ballen38-creator/studentcorner#4]

**Comment by ritwik3856** [comment]
i can do it assign me

**Comment by ballen38-creator** [comment]
> i can do it assign me

Alright.

**Comment by ritwik3856** [comment]
![Uploading design section.jpg…](
![desgin section 2 ](https://user-images.githubusercontent.com/61063842/135791306-b3098253-17e8-431e-a468-6fa45758ae12.jpg)
)
i have to design what the internal section of the pages or just the home page section where all names are written just  clarify ones
explain your issue in detail with screenshot or my file name please

**Comment by ballen38-creator** [comment]
> ![Uploading design section.jpg…]( ![desgin section 2 ](https://user-images.githubusercontent.com/61063842/135791306-b3098253-17e8-431e-a468-6fa45758ae12.jpg) ) i have to design what the internal section of the pages or just the home page section where all names are written just clarify ones explain your issue in detail with screenshot or my file name please

![design](https://user-images.githubusercontent.com/72469365/135797627-4f425e39-0fd7-4a3b-9986-407c82e2feed.jpg)

You don't have to update each subject page. You just need to work on the index.html file. The issue here is the subject tiles section does not have any heading or or some block in which all of them are placed in a manner such that it is easy for people to understand that following are the subjects for which study material is available.

**Comment by ritwik3856** [comment]
Ok thank you for clarification i will do it in less than 24 hr 😁😁😁

**Comment by ballen38-creator** [comment]
This issue has been resolved.
